apiVersion: v1
kind: PersistentVolume
metadata:
  name: website-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "C:\\Users\\Stefano\\Desktop\\K8s casi como en produccion\\static-website"
