apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: website-pv
  storageClassName: ""